import type { RestaurantState } from './restaurantStore.types';

export const initialState: RestaurantState = {
  items: [],
  current: null,
  hasMore: false,
  nextCursor: null,
  isLoading: false,
  isFetching: false,
  error: null,
  orders: [],
  isOrdersLoading: false,
  ordersError: null,
  browseItems: [],
  browseHasMore: false,
  browseNextCursor: null,
  isBrowseLoading: false,
  isBrowseFetching: false,
  browseError: null,
  menuItems: [],
  menuItemsHasMore: false,
  menuItemsNextCursor: null,
  isMenuItemsLoading: false,
  isMenuItemsFetching: false,
  menuItemsError: null,
};

export const RESTAURANT_ACTIONS = {
  LIST_REQUESTED: 'restaurants/listRequested',
  LIST_LOADED: 'restaurants/listLoaded',
  LIST_FETCH_STARTED: 'restaurants/listFetchStarted',
  LIST_APPENDED: 'restaurants/listAppended',
  LIST_FAILED: 'restaurants/listFailed',
  FETCHED: 'restaurants/fetched',
  FETCH_FAILED: 'restaurants/fetchFailed',
  DETAIL_REQUESTED: 'restaurants/detailRequested',
  CREATED: 'restaurants/created',
  UPDATED: 'restaurants/updated',
  DELETED: 'restaurants/deleted',
  CLEARED: 'restaurants/cleared',
  ORDERS_SUBSCRIBED: 'restaurants/ordersSubscribed',
  ORDERS_RECEIVED: 'restaurants/ordersReceived',
  ORDERS_FAILED: 'restaurants/ordersFailed',
  ORDERS_CLEARED: 'restaurants/ordersCleared',
  BROWSE_LIST_REQUESTED: 'restaurants/browseListRequested',
  BROWSE_LIST_LOADED: 'restaurants/browseListLoaded',
  BROWSE_LIST_FETCH_STARTED: 'restaurants/browseListFetchStarted',
  BROWSE_LIST_APPENDED: 'restaurants/browseListAppended',
  BROWSE_LIST_FAILED: 'restaurants/browseListFailed',
  MENU_ITEM_LIST_REQUESTED: 'menuItems/listRequested',
  MENU_ITEM_LIST_LOADED: 'menuItems/listLoaded',
  MENU_ITEM_LIST_FETCH_STARTED: 'menuItems/listFetchStarted',
  MENU_ITEM_LIST_APPENDED: 'menuItems/listAppended',
  MENU_ITEM_LIST_FAILED: 'menuItems/listFailed',
  MENU_ITEM_CREATED: 'menuItems/created',
  MENU_ITEM_UPDATED: 'menuItems/updated',
  MENU_ITEM_DELETED: 'menuItems/deleted',
  MENU_ITEM_CLEARED: 'menuItems/cleared',
} as const;
