import { DEFAULT_CURRENCY } from '@constants/app.constants';
import {
  ORDER_STATUS_LABELS,
  ORDER_TRACKING_STEP_TITLES,
} from '@pages/restaurants/constants/order.constants';

export const DESCRIPTION_MAX_ROWS = 3;

export const DISPLAY = {
  TITLES: {
    CREATE_RESTAURANT: 'Add Restaurant',
    EDIT_RESTAURANT: 'Edit Restaurant',
    MENU_ITEMS: 'Menu',
    CREATE_MENU_ITEM: 'Add Menu Item',
    EDIT_MENU_ITEM: 'Edit Menu Item',
    BROWSE: 'Browse Restaurants',
    RESTAURANT_ORDERS: 'Orders',
    MY_ORDERS: 'My Orders',
    ORDER_SUMMARY: 'Order Summary',
    TRACK_ORDER: 'Track Order',
  },
  LABELS: {
    NAME: 'Name',
    DESCRIPTION: 'Description',
    CUISINE_TYPES: 'Cuisine Types',
    OPENING_TIME: 'Opening Time',
    CLOSING_TIME: 'Closing Time',
    PRICE: `Price (${DEFAULT_CURRENCY.symbol})`,
    IS_VEG: 'Type',
    VEG: 'Veg',
    NON_VEG: 'Non-Veg',
    QUANTITY: 'Quantity',
    IMAGE: 'Image',
    RATING: 'Rating',
    STATUS: 'Status',
    CUISINE: 'Cuisine',
    OPENS: 'Open',
    IMAGE_UPLOAD_HINT: 'JPG, PNG or WEBP. Max 5 MB.',
    SUBTOTAL: 'Subtotal',
    BOOKING_FEE: 'Booking Fee',
    TOTAL: 'Total',
    ITEMS_SELECTED: 'items selected',
    ORDER_STATUS: ORDER_STATUS_LABELS,
    ORDER_ID: 'Order',
    ORDER_TRACKING_STEPS: ORDER_TRACKING_STEP_TITLES,
  },
  ACTIONS: {
    SAVE: 'Save',
    CANCEL: 'Cancel',
    EDIT: 'Edit',
    DELETE: 'Delete',
    ADD_MENU_ITEM: 'Add Item',
    LOAD_MORE: 'Load More',
    GO_TO_ORDERS: 'View Orders',
    UPLOAD_CSV: 'Upload CSV',
    UPLOAD_IMAGE: 'Upload Image',
    BACK: 'Back',
    ADD_TO_CART: 'Add',
    CLEAR_CART: 'Clear Cart',
    PROCEED_TO_ORDER: 'Proceed to Order',
    PLACE_ORDER: 'Place Order',
    CANCEL_ORDER: 'Cancel Order',
    ACCEPT: 'Accept',
    REJECT: 'Reject',
    MARK_PREPARING: 'Mark Preparing',
    MARK_OUT_FOR_DELIVERY: 'Mark Out for Delivery',
    MARK_DELIVERED: 'Mark Delivered',
    TRACK_ORDER: 'Track',
  },
  EMPTY: {
    NO_MENU_ITEMS: 'No menu items yet.',
    NO_RATING: 'No ratings yet',
    NO_RESTAURANTS: 'No restaurants found.',
    NO_ORDERS: 'No orders yet.',
  },
  PLACEHOLDERS: {
    RESTAURANT_NAME: 'e.g. Tandoori Palace',
    RESTAURANT_DESCRIPTION: 'Describe your restaurant...',
    CUISINE_TYPES: 'Select cuisine types',
    MENU_ITEM_NAME: 'e.g. Chicken Biryani',
    MENU_ITEM_DESCRIPTION: 'Describe the dish...',
  },
  FOOD_TYPE: {
    VEG: 'veg',
    NON_VEG: 'nonveg',
  },
  POPCONFIRM: {
    DELETE_RESTAURANT_TITLE: 'Delete this restaurant? This cannot be undone.',
    DELETE_MENU_ITEM_TITLE: 'Delete this item? This cannot be undone.',
    CLEAR_CART_TITLE: (restaurant?: string | null) => {
      return `'Clear your cart? Items from ${restaurant ? `"${restaurant}"` : 'current restaurant'} will be removed.'`;
    },
    CANCEL_ORDER_TITLE: 'Cancel this order?',
    OK_TEXT: 'Yes, delete',
    CANCEL_TEXT: 'No',
  },
  TRACKING: {
    TIME_REMAINING_LABEL: 'Time Remaining',
    RUNNING_LATE: 'This order is taking a little longer than expected.',
    DELIVERED: 'Order Delivered!',
    REJECTED: 'This order was rejected.',
    CANCELLED: 'This order was cancelled.',
  },
} as const;
