import { DEFAULT_CURRENCY } from '@constants/app.constants';

export const DISPLAY = {
  TITLES: {
    DASHBOARD: 'My Restaurants',
    CREATE_RESTAURANT: 'Add Restaurant',
    EDIT_RESTAURANT: 'Edit Restaurant',
    MENU_ITEMS: 'Menu',
    CREATE_MENU_ITEM: 'Add Menu Item',
    EDIT_MENU_ITEM: 'Edit Menu Item',
  },
  LABELS: {
    NAME: 'Name',
    DESCRIPTION: 'Description',
    CUISINE_TYPES: 'Cuisine Types',
    OPENING_TIME: 'Opening Time',
    CLOSING_TIME: 'Closing Time',
    PRICE: `Price (${DEFAULT_CURRENCY.symbol})`,
    IS_VEG: 'Type',
    VEG: 'Veg',
    NON_VEG: 'Non-Veg',
    QUANTITY: 'Quantity',
    IMAGE: 'Image',
    RATING: 'Rating',
    STATUS: 'Status',
    CUISINE: 'Cuisine',
    OPENS: 'Open',
    IMAGE_UPLOAD_HINT: 'JPG, PNG or WEBP. Max 5 MB.',
  },
  ACTIONS: {
    ADD_RESTAURANT: 'Add Restaurant',
    SAVE: 'Save',
    CANCEL: 'Cancel',
    EDIT: 'Edit',
    DELETE: 'Delete',
    ADD_MENU_ITEM: 'Add Item',
    LOAD_MORE: 'Load More',
    GO_TO_ORDERS: 'View Orders',
    UPLOAD_CSV: 'Upload CSV',
    UPLOAD_IMAGE: 'Upload Image',
    BACK: 'Back',
  },
  EMPTY: {
    NO_RESTAURANTS: "You haven't added any restaurants yet.",
    NO_MENU_ITEMS: 'No menu items yet.',
    NO_RATING: 'No ratings yet',
  },
  PLACEHOLDERS: {
    RESTAURANT_NAME: 'e.g. Tandoori Palace',
    RESTAURANT_DESCRIPTION: 'Describe your restaurant...',
    CUISINE_TYPES: 'Select cuisine types',
    MENU_ITEM_NAME: 'e.g. Chicken Biryani',
    MENU_ITEM_DESCRIPTION: 'Describe the dish...',
  },
  FOOD_TYPE: {
    VEG: 'veg',
    NON_VEG: 'nonveg',
  },
  POPCONFIRM: {
    DELETE_RESTAURANT_TITLE: 'Delete this restaurant? This cannot be undone.',
    DELETE_MENU_ITEM_TITLE: 'Delete this item? This cannot be undone.',
    OK_TEXT: 'Yes, delete',
    CANCEL_TEXT: 'No',
  },
} as const;
