import { TAG_COLORS } from '@constants/style.constants';
import type { OrderStatus } from '@pages/restaurants/types/order.types';

export const ORDER_STATUS = {
  PENDING: 'pending',
  ACCEPTED: 'accepted',
  PREPARING: 'preparing',
  OUT_FOR_DELIVERY: 'out_for_delivery',
  DELIVERED: 'delivered',
  REJECTED: 'rejected',
  CANCELLED: 'cancelled',
} as const;

export const ORDER_STATUS_TAG_COLORS: Record<OrderStatus, string> = {
  [ORDER_STATUS.PENDING]: TAG_COLORS.PENDING,
  [ORDER_STATUS.ACCEPTED]: TAG_COLORS.PROCESSING,
  [ORDER_STATUS.PREPARING]: TAG_COLORS.PROCESSING,
  [ORDER_STATUS.OUT_FOR_DELIVERY]: TAG_COLORS.PROCESSING,
  [ORDER_STATUS.DELIVERED]: TAG_COLORS.SUCCESS,
  [ORDER_STATUS.REJECTED]: TAG_COLORS.ERROR,
  [ORDER_STATUS.CANCELLED]: TAG_COLORS.ERROR,
};

export const ORDER_STATUS_LABELS: Record<OrderStatus, string> = {
  [ORDER_STATUS.PENDING]: 'Pending',
  [ORDER_STATUS.ACCEPTED]: 'Accepted',
  [ORDER_STATUS.PREPARING]: 'Preparing',
  [ORDER_STATUS.OUT_FOR_DELIVERY]: 'Out for Delivery',
  [ORDER_STATUS.DELIVERED]: 'Delivered',
  [ORDER_STATUS.REJECTED]: 'Rejected',
  [ORDER_STATUS.CANCELLED]: 'Cancelled',
};

export const BOOKING_FEE = {
  FLAT_AMOUNT: 20,
  PERCENT: 0.01,
} as const;

export const ORDER_TRACKING_STEP_TITLES: Record<OrderStatus, string> = {
  [ORDER_STATUS.PENDING]: 'Order Placed',
  [ORDER_STATUS.ACCEPTED]: 'Accepted',
  [ORDER_STATUS.PREPARING]: 'Preparing',
  [ORDER_STATUS.OUT_FOR_DELIVERY]: 'Out for Delivery',
  [ORDER_STATUS.DELIVERED]: 'Delivered',
  [ORDER_STATUS.REJECTED]: 'Rejected',
  [ORDER_STATUS.CANCELLED]: 'Cancelled',
};

export const ORDER_TRACKING_STAGE_ETA_MINUTES: Record<OrderStatus, number | null> = {
  [ORDER_STATUS.PENDING]: 5,
  [ORDER_STATUS.ACCEPTED]: 5,
  [ORDER_STATUS.PREPARING]: 30,
  [ORDER_STATUS.OUT_FOR_DELIVERY]: 20,
  [ORDER_STATUS.DELIVERED]: null,
  [ORDER_STATUS.REJECTED]: null,
  [ORDER_STATUS.CANCELLED]: null,
};

export const ORDER_TRACKING_TICK_MS = 1000;

export const ORDER_TRACKING_PATH_STATUSES: OrderStatus[] = [
  ORDER_STATUS.PENDING,
  ORDER_STATUS.ACCEPTED,
  ORDER_STATUS.PREPARING,
  ORDER_STATUS.OUT_FOR_DELIVERY,
  ORDER_STATUS.DELIVERED,
];

export const ORDER_TRACKING_TERMINAL_BRANCH_STATUSES: OrderStatus[] = [
  ORDER_STATUS.REJECTED,
  ORDER_STATUS.CANCELLED,
];

export const ORDER_TRACKING_TERMINAL_STATUSES: OrderStatus[] = [
  ORDER_STATUS.DELIVERED,
  ORDER_STATUS.REJECTED,
  ORDER_STATUS.CANCELLED,
];
